stages:
  - build
  - deploy

build prod:
  image: node:10.15.0-stretch
  stage: build
  only:
    - tags
  script:
    # Install dependencies
    - npm install
    # Build App
    - npm run build
  artifacts:
    paths:
      # Build folder
      - dist/
    expire_in: 1 hour

deploy prod:
  image: python:latest
  stage: deploy
  only:
    - tags
  script:
    - pip install awscli
    - aws s3 sync ./dist s3://take.apeun.it

build stage:
  image: node:10.15.0-stretch
  stage: build
  only:
    - develop
  script:
    # Install dependencies
    - npm install
    # Build App
    - npm run build
  artifacts:
    paths:
      # Build folder
      - dist/
    expire_in: 1 hour

deploy stage:
  image: python:latest
  stage: deploy
  only:
    - develop
  script:
    - pip install awscli
    - aws s3 sync ./dist s3://take.apeun.it
    #- aws cloudfront create-invalidation --distribution-id $CF_DISTRIBUTION_ID --paths '/*'
